server:
  port: 6666

spring:
  redis:
    host: 127.0.0.1
    port: 5731
    password: redis92
    jedis:
      pool:
        max-active: 8
        max-wait: -1
        max-idle: 8
        min-idle: 0

